Class {
	#name : #AVIDEOGeneratedDoIt,
	#superclass : #Object,
	#category : 'AbstractVideo-GeneratedPharo'
}

{ #category : #'initialization' }
AVIDEOGeneratedDoIt class >> initializeConstants [
	<script>
	AVIDEOTypes initialize.
	AVIDEOConstants initialize.
]

{ #category : #'initialization' }
AVIDEOGeneratedDoIt class >> initializeStructures [
	<script>
	AVIDEOContextOpenInfo rebuildFieldAccessors.
]

{ #category : #'initialization' }
AVIDEOGeneratedDoIt class >> initializeBindings [
	<script>
	self initializeConstants.
	self initializeStructures.
]

